### ISSUE TITLE
False positive in UnusedPrivateMethod

### ISSUE THREAD

**Issue by MEZk** [codacy/codacy-pmdjava#14]
Hello!

We use Codacy CI to check PRs in [Checkstyle](https://github.com/checkstyle/checkstyle) repo with the following [configuration](https://github.com/codacy/codacy-pmdjava/files/238635/codacy-conf_new_v2.zip). PMD's check (UnusedPrivateMethod) which is used in Codacy reports that method [verifyWarnd](https://github.com/checkstyle/checkstyle/blob/f111cc06fb4744981f79173db4659b8a8f12d5aa/src/test/java/com/puppycrawl/tools/checkstyle/checks/indentation/IndentationCheckTest.java#L152) is unused, however, it is used multiple times in the class IndentationCheckTest where it is declared. We also use maven pmd plugin and the rule UnusedPrivateMethod from PMD and it does not report any violations for 'verifyWarnd' method. So, I think it is Codacy's issue. Now we have to exclude the method from the validation as you can see from the configuration.

Please, contact me if you need more details.

**Comment by machadoit** [comment]
Hey @MEZk 

We'll take a look at that, can you send us an example of your code that have the false positives? So we can add it to our tests. Also, which version of PMD are you using?

**Comment by machadoit** [comment]
The problem was with the pmd 5.3.6, updating to 5.4.1 will remove your false positive =) Will let you know when we have the new version deployed!

**Comment by machadoit** [comment]
Fixed by https://github.com/codacy/codacy-pmdjava/commit/c5ce79b4fcd3a203c24a0e633b465a7980070dac

By the end of the day, the new version will be used by Codacy, you can revert your configuration and re-analyse to get the expected result :)

**Comment by MEZk** [comment]
@machadoit 
Thanks a lot
