### ISSUE TITLE
Support for new PMD rules required?

### ISSUE THREAD

**Issue by mweirauch** [codacy/codacy-pmdjava#18]
I am not quite sure I've understood the technical details entirely ...

Does `codacy-pmdjava` understand any rule the underlying `pmd` version supports or is there a need for an explicit "mapping" within this project here in order to support the rules the underlying `pmd` supports? (The code indicates this if I am not mistaken.)

I am asking because `pmd` was upgraded from 5.3.6 to 5.4.1 in April. I am missing `rulesets/java/comments.xml/CommentDefaultAccessModifier` introduced with `5.4.0` which can act as a "saner" replacement for `rulesets/java/controversial.xml/DefaultPackage`.

**Comment by machadoit** [comment]
We need to have a mapping on our .json. You can check both .json that I have to edit to fix the parameters of a a code check: https://github.com/codacy/codacy-pmdjava/commit/562c8cfa62c88c6aeb76a42d5ae80ea62ee5cb72

Regarding our tool integration on Codacy, you can check the https://github.com/codacy/codacy-pmdjava#docs on this readme. There we have information about everything that a docker needs to run a tool on Codacy.

So feel free to PR the missing pattern, we will eventually add it during a future review of PMD, but for now, the fastest way would be a PR from you. Let me know if you need any help!

**Comment by mweirauch** [comment]
Thanks for your answer. I'll see what I can do.
