### ISSUE TITLE
Support Visualforce language with 5.6.0 PMD release

### ISSUE THREAD

**Issue by up2go-rsoesemann** [codacy/codacy-pmdjava#27]
We recently added PMD support for the markup language Visualforce 
https://github.com/pmd/pmd/tree/master/pmd-visualforce

It would be great if Codacy would support it as well.

**Comment by rtfpessoa** [comment]
Is this in release 5.5.4 already?

**Comment by up2go-rsoesemann** [comment]
This has been merged and will be included in PMD 5.6.0 and later. I just though there might be a lot to prepare ...;-)

**Comment by rtfpessoa** [comment]
Is there any prerelease of the jars I can use?

**Comment by up2go-rsoesemann** [comment]
@rtfpessoa it's a snapshot you can download here: http://pmd.sourceforge.net/snapshot/

**Comment by up2go-rsoesemann** [comment]
https://github.com/pmd/pmd/milestone/2 is scheduled for end of April

**Comment by up2go-rsoesemann** [comment]
@rtfpessoa I saw that you upgraded docker to PMD 5.6.0. But I guess there needs to be also some changes to the UI, right. Apply VF rules to .page files and the like.

**Comment by rtfpessoa** [comment]
Yup. We are working on it. Will post updates when ready.

**Comment by rtfpessoa** [comment]
I completly missed this. This is also in prod. Sorry for the late update.
