### ISSUE TITLE
Make Salesforce *.resource files work in CSS + JS engines

### ISSUE THREAD

**Issue by up2go-rsoesemann** [codacy/codacy-pmdjava#28]
As discussed with  @rtfpessoa: 

CSS and JS files in Salesforce all end with the same extension. There is a convention to name them *_css.resource or _js.resource

Allowing wildcards would do the trick

**Comment by rtfpessoa** [comment]
What are the engines you would be interested to run?

Examples: ESLint, CSSLint, StyleLint, SCSSLint, PMD (for Javascript)?

I think we might need to do a case by case fix.

Do you have any more extensions besides `_css.resource` or `_js.resource`, I am not sure if just sending the files to the tool will do it in all of them. I know at least ESLint for example for JSX needs a CLI parameter to analyse the jsx files.

**Comment by up2go-rsoesemann** [comment]
PMD for Javascript is somewhat outdated. So no.
Currently we use ESLint and CSSLint as CodeClimate was able to make them recognize .resource files. For details see this conf file: https://github.com/Up2Go/travelexpenses/blob/master/.codeclimate.yml

The mentioned 2 extensions are just our internal convention. The most Saelsforce Devs use .resource for both. So I would go with a flexible wildcard-based solution.

**Comment by rtfpessoa** [comment]
@up2go-rsoesemann we just released support for custom language extensions.

An example `.codacy.yml` would be:

```yaml
---
languages:
  css:
    extensions:
      - "-css.resource"
```

Check this docs for more details: https://codacy.zendesk.com/hc/en-us/articles/115002130625

Note that some tools might not work out of the box with the custom extensions, so if you see any problem let me know so I can take a look.

**Comment by up2go-rsoesemann** [comment]
That' fantastic. I will check this out with all of my repos immediatelly.

**Comment by up2go-rsoesemann** [comment]
As discussed. it seems to work with a .yml file but when I use those file extensions in the Settings UI `*_js.resource ` is converted `.*_js.resource `

**Comment by rtfpessoa** [comment]
This should be fixed. If you use `_css.resource` it should match the files.
