### ISSUE TITLE
Time to fix always shows 5min

### ISSUE THREAD

**Issue by up2go-rsoesemann** [codacy/codacy-pmdjava#29]
<img width="653" alt="cursor_und_2team_-_codacy_-_issues" src="https://cloud.githubusercontent.com/assets/8180281/23700704/f03a3c18-03f3-11e7-9e83-d5b4966d8c6f.png">

Couldn't we use an engine specific parameter as we did for Code Climate. They use a complicated Remediation Point system. Why not have a "time to fix in minutes" which also can be null which means "depends".

**Comment by rtfpessoa** [comment]
Currently I only read the files defined in the `rules.properties` to get the name etc.
Can we have the remediation points in the ruleset xml files? Also what would be the best way to map remediation points to time?

**Comment by up2go-rsoesemann** [comment]
There are not so many people using CodeClimate yet so instead using the remediation points I suggest adding Codacy specific params.

So in my repositories I would extend this https://github.com/Up2Go/travelexpenses/blob/master/apex-ruleset.xml by adding a few lines per rule:

```
<rule ref="rulesets/apex/complexity.xml/IfWithoutbraces" message="...">
		<priority>3</priority>
		<properties>
        	<property name="minimum" value="1000"/>
        	
        	<!-- relevant for Code Climate output only -->
        	<property name="cc_categories" value="Complexity"/>
        	<property name="cc_remediation_points_multiplier" value="100"/>
        	<property name="cc_block_highlighting" value="false"/>
        	
        	<!-- relevant for Codacy output only -->
        	<property name="cy_categories" value="Complexity"/>
        	<property name="cy_minutes_to_fix" value="1"/>
    	</properties>	
```

**Comment by rtfpessoa** [comment]
This sounds good to me.

**Comment by up2go-rsoesemann** [comment]
@rtfpessoa should I update the apex-ruleset.xml to have times to fix properties?

**Comment by rtfpessoa** [comment]
That would be amazing.
I would definitely be more confortable with your times.

**Comment by up2go-rsoesemann** [comment]
@jsotuyod / @adangel: Can I package an apex specific ruleset with pmd? Instead of only having it in the tool repos that use PMD I would like to package it inside of PMD.

**Comment by up2go-rsoesemann** [comment]
@rtfpessoa I will give each rule one of those fixed values:

- a work week of 5 days and 6 effective hours : 1800 min
- a work day of 6 effective hours : 360 min
- an hour : 60 min
- minimum effort: 10 min

**Comment by rtfpessoa** [comment]
Ok, nice.

**Comment by up2go-rsoesemann** [comment]
Merged to PMD but not made it into PMD 5.6.0. Will be released in May.

**Comment by up2go-rsoesemann** [comment]
I will leave this open until I see how the numbers show up. Are you already parsing the new property?

**Comment by rtfpessoa** [comment]
Not yet. Need to do some changes.

**Comment by up2go-rsoesemann** [comment]
@rtfpessoa The PMD maintainer rejected an Apex/Visualforce only solution of the problem in PMD and instead suggest an alternative solution where the required artefacts are generated by you plugin. Sounds good to me as we keep coupling between Codacy and PMD low.

Could you please check @adangel's comments here https://github.com/pmd/pmd/pull/329#discussion_r112703324 and tell me if you are willing to support that solution. Time to fix is an important feature.

**Comment by rtfpessoa** [comment]
Just made a quick update that uses the timeToFix you specified. For new rules we just need to add more lines in the same place #38

**Comment by rtfpessoa** [comment]
This is in prod and even for old issues they should already reflect the new values.

**Comment by up2go-rsoesemann** [comment]
But aren't the PMD maintainers rejecting our solution?! I am confused. 

@rtfpessoa Can you please elaborate a bit on how you solved this and how developer can override the ttf values per repo.

**Comment by rtfpessoa** [comment]
I did your suggestion in #38 and for now when you have more times just add to the list in a PR here and it will appear in Codacy in the next versions.
