### ISSUE TITLE
[feature] As a ruleset admin I want to see if and why my ruleset made PMD fail

### ISSUE THREAD

**Issue by up2go-rsoesemann** [codacy/codacy-pmdjava#33]
When there are errors in the custom ruleset.xml the engine silently fails without giving any notice. In Code Climate there is a status for each commit with a very detail error output showing why an engine failed.

As I expect users of this engine to play around a lot with their ruleset.xml this is a crucial feature.

**Comment by up2go-rsoesemann** [comment]
@rtfpessoa any updates on that. You might remember that an error in the conf file made the checks fails without giving notice to anybody.

**Comment by rtfpessoa** [comment]
We are definitely implementing something to give the users more information about the failures but I  do not have a timeline for that.

In the meanwhile do not hesitate to reach support for help with any failures.

**Comment by up2go-rsoesemann** [comment]
Can I leave this open as a reminder?

**Comment by rtfpessoa** [comment]
This feature is in production. You can check this inside the commits or prs if you click in `View Logs`.
