### ISSUE TITLE
Cannot find clear definition of the default Codacy PMD ruleset

### ISSUE THREAD

**Issue by calbach** [codacy/codacy-pmdjava#49]
I would like to move to a ruleset.xml in my repo. Ideally I would start with the same ruleset used by Codacy by default. I cannot find where this is defined.

**Comment by rtfpessoa** [comment]
@calbach at the moment we do not have a way to export the default rules since it is passed from 
 the ui inside the product and if only generated at runtime.

**Comment by calbach** [comment]
Thanks. On that suggestion, by any chance do you have a pointer to a repo with a working Codacy + rules.xml config? I tried generating a config file via http://pmd.sourceforge.net/pmd-5.1.1/howtomakearuleset.html and received no issues in Codacy (and no error feedback in the UI).

**Comment by rtfpessoa** [comment]
@calbach can you contact Codacy support? You can do it through the app or by email at support at codacy dot com. They will be able to check the exact project and give some help with the file.
