### ISSUE TITLE
Package private test methods with JUnit 5

### ISSUE THREAD

**Issue by jordanjennings** [codacy/codacy-pmdjava#54]
I'm using a project with JUnit 5 and I'd like to follow the default JUnit 5 recommendation of using package private tests. See here: https://junit.org/junit5/docs/current/user-guide/#writing-tests-classes-and-methods, specifically the note:

>Neither test classes nor test methods need to be public

The default PMD configuration for Codacy complains if I use package private test methods. It shows:

![image](https://user-images.githubusercontent.com/1031913/52083162-b41ce900-256c-11e9-9ed7-7a5a69f4ce1e.png)

Can default Codacy PMD configuration be adjusted to properly allow package private JUnit 5 tests? I really don't want to go to a custom XML ruleset just for a small tweak. In the meanwhile I'm just making the tests public but then other tooling that does follow the JUnit 5 recommendation needs tweaking. Thanks!

**Comment by jordanjennings** [comment]
Is Codacy's Java integration maintained?

**Comment by IGFCoimbra** [comment]
Hi @jordanjennings 

I'm very sorry for the time it took us to get back to you.

If you still getting those issues, please reach out to support@codacy.com so we can help you get this fixed.

Regards,
Ivo

**Comment by seancarroll** [comment]
It would be nice if the default tool pattern list accounted for this but I suppose its not too much trouble to define a custom PMD ruleset

**Comment by lolgab** [comment]
Thank you @jordanjennings and @seancarroll for letting us know. We changed the default rules to exclude [DefaultPackage](https://pmd.github.io/pmd-6.18.0/pmd_rules_java_codestyle.html#defaultpackage) since it triggers false positives on JUnit5 code.
