### ISSUE TITLE
Leverage Github Checks API

### ISSUE THREAD

**Issue by rsoesemann** [codacy/codacy-pmdjava#55]
Just discovered https://help.github.com/articles/about-status-checks/#checks.

Are there any plans to use that for Codacy. It would be really nice if Codacy results would be shown directly inside the GitHub UI.

**Comment by IGFCoimbra** [comment]
Hi @rsoesemann 

I'm very sorry for the time it took to get back to you.

On the Github checks, I have shared your idea with our product team so they can check and act on this.

If you have any other question, please reach out to support@codacy.com

Regards,
Ivo
