### ISSUE TITLE
Support for incremental analysis?

### ISSUE THREAD

**Issue by Plazmaz** [codacy/codacy-pmdjava#72]
Hi, it seems like there could be a significant speed improvement if you mounted a cache directory onto the container and used PMD's [Incremental Anaylsis](https://pmd.github.io/pmd-6.14.0/pmd_userdocs_incremental_analysis.html) mode. Is this something that's been considered?

**Comment by ljmf00** [comment]
Hey @Plazmaz ,

Unfortunately, we currently don't support incremental analysis in the tools, but instead, we have an agnostic cache by running only the files that changed, making almost the same expected behavior. This is our approach to not depend on the this tool feature.

Thanks,
Luís

**Comment by Plazmaz** [comment]
Ah okay. Thanks for the context.
