### ISSUE TITLE
PMD DocGenerator generates strange pattern titles

### ISSUE THREAD

**Issue by lolgab** [codacy/codacy-pmdjava#73]
PMD DocGenerator uses the message as pattern title for the documentation.
Sometimes this choice is far from ideal: "`The method {0}() has an NCSS line count of {1}`".

We want, instead, use the pattern title converting from CamelCase to a sentence:
`ExcessiveMethodLength` should become: `Excessive method length`

It should manage constants names with all upper case letters:
`TO_TIMESTAMPWithoutDateFormat` should become: `TO_TIMESTAMP without date format`

**Comment by mrfyda** [comment]
@lolgab can you add more details to this one?

**Comment by lolgab** [comment]
Done ✅
